### ISSUE TITLE
utf-8 name in xsd

### ISSUE THREAD

**Issue by norguhtar** [droyo/go-xml#127]
It supported? I try generate code by xsd with utf-8 name and got nothing. xsd file in attach

[xsd.zip](https://github.com/droyo/go-xml/files/5702704/xsd.zip)

**Comment by droyo** [comment]
utf-8 is supported. The script must support capitalization, so scripts like Cyrillic here, Latin, Greek, etc should be fine. This comes from Go's use of capitalization for public/private distinction.

The reason you see no output is because the schema does not define a `targetNamespace`, and `xsdgen` doesn't like that. However, since you only have a single schema file, you can do this:

    xsdgen -ns "" PD_ON_1_891_00_05_02_01.utf.xsd

And it will produce [this output](https://gist.github.com/droyo/604d306ec1880d47d735dab16df619e2#file-gistfile1-txt) which seems to be OK.

**Comment by norguhtar** [comment]
Thanks it helps. Why you not set this ns by default?

**Comment by droyo** [comment]
I did not know there were schema without `targetNamespace` when I built the tool.

I could change the default, but there are some bugs. `xsdgen` doesn't really support multiple schema with no targetNamespace very well. I'd like to resolve #121 first.
