### ISSUE TITLE
Amazon MWS schema gives empty generated go file

### ISSUE THREAD

**Issue by nikolay-turpitko** [droyo/go-xml#15]
I'm trying to generate go code from Amazon MWS xsd schema.
Below are files to reproduce the issue:

    $ cat ./generate-amazon-mws-from-xsd
    #!/bin/bash
    wget -N -P zzz -i ./amazon-mws-xsd-urls -B "https://images-na.ssl-images-
    amazon.com/images/G/01/rainier/help/xsd/release_4_1/"
    cd xxx
    go generate
    
    $ cat ./amazon-mws-xsd-urls
    amzn-envelope.xsd
    amzn-header.xsd
    amzn-base.xsd
    Inventory.xsd
    Price.xsd
    OrderAcknowledgement.xsd
    OrderFulfillment.xsd
    
    $ cat ./xxx/xxx.go 
    package main
    
    //go:generate xsdgen ../zzz/amzn-base.xsd ../zzz/Price.xsd

Namely, first file is a bash script to download schema files, second file is a list of required files and third is a go file with `go generate` directive.

First of all, I had to change `aqwari.net/xml/xsd/parse.go#parseInt()` as following:

	func parseInt(s string) int {
		s = strings.TrimSpace(s)
		switch s {
		case "":
			return 0
		case "unbounded":
			return -1
		}
		n, err := strconv.Atoi(s)
		if err != nil {
			//TNL: attempt to parse from float
			f, err := strconv.ParseFloat(s, 64)
			if err != nil {
				stop(err.Error())
			}
			n = int(f)
		}
		return n
	}

otherwise it failed to parse `<xsd:minInclusive value=".01"/>` on restriction on `xsd:decimal` type.

This is an issue by itself, but I want just to fast generate go structs and edit them manually, so I don't bother with validations for the moment.

After that, `go generate` finished without error, but created an empty output file with only `package` directive in it.

I also tried to put schema files into the same dir as go file, path is under $GOPATH/src.

Could you please suggest what am I doing wrong or suggest a quick workaround till it fixed?

**Comment by droyo** [comment]
Thanks for catching the issue with minInclusive et al. Just pushed a fix for that.

I've looked at these schema and the first thing that jumps out at me is there's no target namespace. The `xsdgen` tool looks for the `targetNamespace` attribute on all schema and by default will generate type declarations for all target namespaces. I neglected to handle the case of *no* name space, detailed here in the spec: https://www.w3.org/TR/xmlschema-0/#UndeclaredTNS .

I tried adding `targetNamespace=""` to all the xsd, but hit the following error:

        could not dereference {{http://www.w3.org/2001/XMLSchema element} [{{ ref} CatPIL}]}

That was due to a missing CatPIL.xsd. I tried fetching all the xsd and resorted to finding a repo online (https://github.com/anichelabs/amz-mws-xsd). After running against that, I got

        complexType _anon353: could not find type "ItemLongStringNotNull" in namespace  for element value

I couldn't find where that type was defined.

**Comment by nikolay-turpitko** [comment]
@droyo Thank you for trying help.

First of all, I should say, that I found a workaround for task at hand, so don't worry about that.

Just FYI: as a workaround I used `xsd2inst` tool from Apach xmlbeans to generate sample xml by xsd and generated Go structs from sample xml with `xmljson2struct` tool (github.com/wicast/xj2s). I also tried `github.com/gnewton/chidley`, but didn't like it's output - too much redundant code. BTW, this is an example of the code, I hoped to have from the tool (this is an output of `xsd2inst`):

    type OrderAcknowledgement struct {
            MerchantOrderID string  `xml:"MerchantOrderID"`
            StatusCode      string  `xml:"StatusCode"`
            AmazonOrderItemCode     string  `xml:"Item>AmazonOrderItemCode"`
            MerchantOrderItemID     string  `xml:"Item>MerchantOrderItemID"`
            CancelReason    string  `xml:"Item>CancelReason"`
            AmazonOrderID   string  `xml:"AmazonOrderID"`
    }

This is just to have an idea what I was looking for.

Next, regarding to nemespace issue, it's strange for me, because I was able to run your tool without errors with script and fix I described in the first message. Namely, all xml dependencies could be resolved with `amzn-base.xsd`. Only be warned, that Amazon has several versions of schema files, you should have all files from the single source for consistence. If you can use `bash` and `curl` please use exact command I provided - I found, that without last slash it downloads wrong version. Also, you could try to use this repo: https://raw.githubusercontent.com/highsource/jsonix-support/master/a/amzn/original-schemas/. But I'am sure, that URL and schema names from Amazon I provided earlier should be enough - I used them with other tools without any issues. BTW, there are no reference to "ItemLongStringNotNull" within my copy of schema.

**Comment by droyo** [comment]
Thanks for your input.

I went back and followed your exact instructions, and you were right, the schema you provided are sufficient. After applying your fix and a fix to #16, I was able to generate schema by changing

    //go:generate xsdgen ../zzz/amzn-base.xsd ../zzz/Price.xsd

to

    //go:generate xsdgen -ns "" ../zzz/amzn-base.xsd ../zzz/Price.xsd


Here is what the declaration looks like for the type you provided:
	
	type Anon1 struct {
		AmazonOrderID       AmazonOrderID       `xml:" AmazonOrderID"`
		MerchantOrderID     string              `xml:" MerchantOrderID"`
		StatusCode          StatusCode          `xml:" StatusCode"`
		Item                []Item              `xml:" Item"`
		AmazonOrderItemCode AmazonOrderItemCode `xml:" AmazonOrderItemCode"`
		MerchantOrderItemID string              `xml:" MerchantOrderItemID"`
		CancelReason        CancelReason        `xml:" CancelReason"`
	}
	
	// May be one of NoInventory, ShippingAddressUndeliverable, CustomerExchange, BuyerCanceled, GeneralAdjustment, CarrierCreditDecision, RiskAssessmentInformationNotValid, CarrierCoverageFailure, CustomerReturn, MerchandiseNotReceived
	type CancelReason string
	
	type Item struct {
		AmazonOrderItemCode AmazonOrderItemCode `xml:" AmazonOrderItemCode"`
		MerchantOrderItemID string              `xml:" MerchantOrderItemID"`
		CancelReason        CancelReason        `xml:" CancelReason"`
	}
	
	// Must match the pattern \d{14}
	type AmazonOrderItemCode string

The type name is Anon1 due to #14

**Comment by droyo** [comment]
So a couple things:

- xsdgen (command nor package) doesn't fetch dependent schema for you; you have to specify all relevant files on the command line. Resolving all dependencies recursively would be a good feature (or separate command). Sometimes that's hard because the <import> or <include> statements don't have consistent URIs (or none at all).
- There's a bug in [lookupTargetNS](https://github.com/droyo/go-xml/blob/668f7487e75e41c20f62d79bfd25008ea3d5fa2a/xsdgen/xsdgen.go#L42) that necessitated the `-ns ""` workaround. I neglected to consider the case when no target namespace is considered.

**Comment by nikolay-turpitko** [comment]
@droyo Thank you! With `-ns ""` I was able to generate Go file. I think, this issue can be closed now.
