### ISSUE TITLE
fail to build base64Binary type

### ISSUE THREAD

**Issue by flisky** [droyo/go-xml#18]
The generated definition:
```
type base64Binary []byte

func (b base64Binary) UnmarshalText(text []byte) (err error) {
	*b, err = base64.StdEncoding.DecodeString(string(text))
	return err
}
func (b base64Binary) MarshalText() ([]byte, error) {
	var buf bytes.Buffer
	enc := base64.NewEncoder(base64.StdEncoding, &buf)
	enc.Write([]byte(b))
	enc.Close()
	return buf.Bytes()
}
```

There are 3 problems:

1. `*b, err = base64.StdEncoding.DecodeString(string(text))` failed as `invalid indirect of b (type base64Binary)`

2. `MarshalText` failed as `not enough arguments to return`

3. The corresponding fields actually are not in `base64Binary` type.

**Comment by droyo** [comment]
I looked into this further. Besides the easy-to-fix problems in the method template, the `xsdgen` package does not correctly handle types that extend or restrict *any* of the non-trivial builtin types (`base64Binary`, `hexBinary`, `xsdDate`, anything in [xsdgen/xsdgen.go#L349-L360](https://github.com/droyo/go-xml/blob/ccd94b127cc05abec788aff768d7f23fe88b5d0e/xsdgen/xsdgen.go#L349-L360)).

The code that handles these "special" builtins is quite messy, so I'm going to write some tests and try to refactor it.

**Comment by droyo** [comment]
I'm getting there. My main goal is making the generated types easy to use and hiding all the XML ugliness. A more distant secondary goal is keeping the generated code "simple" (according to my subjective definition of "simple"). Given xsd like this:

	<complexType name="MyType">
	  <sequence>
	    <element name="name" type="string"/>
	    <element name="data" type="base64Binary"/>
	  </sequence>
	</complexType>

The following generated code is fairly simple.

	type Base64Binary []byte
	
	func (x *Base64Binary) UnmarshalText(text []byte) error {
		...
	}
	
	func (x Base64Binary) MarshalText() ([]byte, error) {
		...
	}

	type MyType struct {
		Name string `xml:"name"`
		Data Base64Binary `xml:"data"`
	}

However, while this is probably one of the more simple approaches, I don't like it for a few reasons:

- Looking at the decl for `MyType`, it's not immediately clear to the user what `Data` is, how to read it, and how to write it. Since it's called `Base64Binary`, do I have to encode the bytes I assign to it? (incorrect assumption, the Marshal/Unmarshal methods take are of that)
- Why do I need to know about `Base64Binary` at all? It's an implementation detail and shouldn't pollute my godoc page.

I much prefer a type declaration like this:

	type MyType struct {
		Name string
		Data []byte
	}

The question is, how do we write the marshal/unmarshal methods? The key challenge is to override the unmarshaling specific fields in a `struct` without introducing extra types into the public declaration. I've been doing some experimenting, and I think something like this would work: https://play.golang.org/p/wWIXrHIMNU . In short, embed the type in an anonymous type, containing private type overrides for any non-trivial builtins (time, day, month, hexbinary, base64binary etc).

Marshalling seems like an easier problem, but the technique above may prove useful there, too.

**Comment by droyo** [comment]
After PR #24  I'm pretty happy with the quality of the generated code. The generating code has gotten more messy, but that's OK, it doesn't end up in users' codebases :) . I've only verified that valid Go code is generated for a few examples; I haven't actually tried a Marshal/Unmarshal of real data, so I'll leave this open until I can verify it works for straightforward types.

**Comment by flisky** [comment]
Thanks for making it happen! We will give a try in a few days.

**Comment by droyo** [comment]
The tests introduced in #26 exercise marshal/unmarshal for the time, hexBinary, and base64Binary builtins. They uncovered a bug, too, which has been fixed.

One small gotcha with this approach is that it changes the order of the output when marshalling a type back into XML. Any "overrided" types get put at the end, instead of the order they are declared in the XSD. I don't see this being a problem worth working around.

Since this has been tested, I'll close this issue. Feel free to open a new one if you have any problems.
